version: '3'

services:

  server:
    container_name: 'laravel8-practice-server'
    image: nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf/site-default.conf:/etc/nginx/conf.d/default.conf
      - ./server:/srv:cached
    depends_on:
      - php-fpm

  php-fpm:
    container_name: 'laravel8-practice-php-fpm'
    build: ./docker/php-fpm
    restart: on-failure
    volumes:
      - ./server:/srv:cached

  composer:
    container_name: 'laravel8-practice-composer'
    image: composer
    command: 'composer install -o --ignore-platform-reqs'
    volumes:
      - ./server:/srv:delegated
    working_dir: /srv
